apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-database
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-database
  template:
    metadata:
      labels:
        app: metadata-database
    spec:
      containers:
        - name: metadata-database
          image: ${METADATA_DATABASE_IMAGE}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: epos-env
          volumeMounts:
            - name: psqldata
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: psqldata
          persistentVolumeClaim:
            claimName: psqldata
