apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-access-service
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-access-service
  template:
    metadata:
      labels:
        app: external-access-service
    spec:
      containers:
        - name: external-access-service
          image: ${EXTERNAL_ACCESS_IMAGE}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: epos-env
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl --fail --silent http://localhost:8080/api/external-access-service/v1/actuator/health | grep UP || exit 1
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - curl --fail --silent http://localhost:8080/api/external-access-service/v1/actuator/health | grep UP || exit 1
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
