{{- if .Values.components.converter.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: converter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "epos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: converter-service
  template:
    metadata:
      labels:
        {{- include "epos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: converter-service
    spec:
      {{- include "epos.imagePullSecrets" . | nindent 6 }}
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |-
          until nc -z rabbitmq 5672; do
            sleep 1;
          done
      - name: wait-for-metadata-database
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |-
          until nc -z metadata-database 5432; do
            sleep 1;
          done
      containers:
      - name: converter-service
        image: {{ .Values.images.converter_service_image }}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: converter-service
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - wget -q -O - http://localhost:8080/api/converter-service/v1/actuator/health | grep -i 'healthy'
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - wget -q -O - http://localhost:8080/api/converter-service/v1/actuator/health | grep -i 'healthy'
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: converter-data
          mountPath: /data
      volumes:
      - name: converter-data
        emptyDir: {}
      {{- include "epos.nodeSelector" . | nindent 6 }}
      {{- include "epos.tolerations" . | nindent 6 }}
      {{- include "epos.affinity" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: converter-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    {{- include "epos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: converter-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: converter-service
data:
  LOG_LEVEL: "INFO"
  BROKER_HOST: rabbitmq
  BROKER_USERNAME: {{ .Values.components.rabbitmq.username }}
  BROKER_PASSWORD: {{ .Values.components.rabbitmq.password }}
  BROKER_VHOST: {{ .Values.components.rabbitmq.vhost }}
  POSTGRESQL_CONNECTION_STRING: "{{ include "epos.postgresqlConnectionString" . }}"
{{- end }}
