---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: resources-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "epos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: resources-service
  template:
    metadata:
      labels:
        {{- include "epos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: resources-service
    spec:
      {{- include "epos.imagePullSecrets" . | nindent 6 }}
      initContainers:
      - name: wait-for-metadata-database
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |-
          until nc -z metadata-database 5432; do
            sleep 1;
          done
      - name: wait-for-rabbitmq
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |-
          until nc -z rabbitmq 5672; do
            sleep 1;
          done
      containers:
      - name: resources-service
        image: {{ .Values.images.resources_service_image }}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: resources-service
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --silent http://localhost:8080/api/resources-service/v1/actuator/health | grep UP || exit 1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --silent http://localhost:8080/api/resources-service/v1/actuator/health | grep UP || exit 1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
      {{- include "epos.nodeSelector" . | nindent 6 }}
      {{- include "epos.tolerations" . | nindent 6 }}
      {{- include "epos.affinity" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: resources-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: resources-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    {{- include "epos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: resources-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: resources-service
data:
  PERSISTENCE_NAME: "EPOSDataModel"
  POSTGRESQL_CONNECTION_STRING: "{{ include "epos.postgresqlConnectionString" . }}"
  CONNECTION_POOL_INIT_SIZE: {{ .Values.components.metadata_database.connection_pool_init_size | quote }}
  CONNECTION_POOL_MIN_SIZE: {{ .Values.components.metadata_database.connection_pool_min_size | quote }}
  CONNECTION_POOL_MAX_SIZE: {{ .Values.components.metadata_database.connection_pool_max_size | quote }}

  FACETS_DEFAULT: "true"
  FACETS_TYPE_DEFAULT: "categories"

  APICONTEXT: "/api/v1"

  APIHOST: http://gateway:5000/ # TODO: fix this to be the external gateway url

  MONITORING: "{{ .Values.monitoring.enabled }}"
  {{- if .Values.monitoring.enabled }}
  MONITORING_URL: {{ .Values.monitoring.url }}
  MONITORING_USER: {{ .Values.monitoring.user }}
  MONITORING_PWD: {{ .Values.monitoring.password }}
  {{- end }}

  CACHE_TTL: {{ .Values.components.resources_service.cache_ttl | quote }}

  BROKER_HOST: rabbitmq
  BROKER_USERNAME: {{ .Values.components.rabbitmq.username }}
  BROKER_PASSWORD: {{ .Values.components.rabbitmq.password }}
  BROKER_VHOST: {{ .Values.components.rabbitmq.vhost }}
