{{- if .Values.components.email_sender_service.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-sender-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: email-sender-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "epos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: email-sender-service
  template:
    metadata:
      labels:
        {{- include "epos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: email-sender-service
    spec:
      {{- include "epos.imagePullSecrets" . | nindent 6 }}
      initContainers:
      - name: wait-for-metadata-database
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |-
          until nc -z metadata-database 5432; do
            sleep 1;
          done
      containers:
      - name: email-sender-service
        image: {{ .Values.images.email_sender_service_image }}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: email-sender-service
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --silent http://localhost:8080/api/email-sender-service/v1/actuator/health | grep UP || exit 1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --fail --silent http://localhost:8080/api/email-sender-service/v1/actuator/health | grep UP || exit 1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
      {{- include "epos.nodeSelector" . | nindent 6 }}
      {{- include "epos.tolerations" . | nindent 6 }}
      {{- include "epos.affinity" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: email-sender-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: email-sender-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    {{- include "epos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: email-sender-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: email-sender-service
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: email-sender-service
data:
  ENVIRONMENT_TYPE: {{ .Values.components.email_sender_service.environment_type }}
  SENDER: {{ .Values.components.email_sender_service.sender }}
  SENDER_NAME: {{ .Values.components.email_sender_service.sender_name }}
  MAIL_TYPE: {{ .Values.components.email_sender_service.mail_type }}
  SENDER_DOMAIN: {{ .Values.components.email_sender_service.sender_domain }}
  MAIL_HOST: {{ .Values.components.email_sender_service.mail_host }}
  MAIL_USER: {{ .Values.components.email_sender_service.mail_user }}
  MAIL_PASSWORD: {{ .Values.components.email_sender_service.mail_password }}
  DEV_EMAILS: {{ .Values.components.email_sender_service.dev_emails }}
  MAIL_API_URL: {{ .Values.components.email_sender_service.mail_api_url }}
  MAIL_API_KEY: {{ .Values.components.email_sender_service.mail_api_key }}
  PERSISTENCE_NAME: "EPOSDataModel"

  CONNECTION_POOL_INIT_SIZE: {{ .Values.components.metadata_database.connection_pool_init_size | quote }}
  CONNECTION_POOL_MIN_SIZE: {{ .Values.components.metadata_database.connection_pool_min_size | quote }}
  CONNECTION_POOL_MAX_SIZE: {{ .Values.components.metadata_database.connection_pool_max_size | quote }}
  POSTGRESQL_CONNECTION_STRING: "{{ include "epos.postgresqlConnectionString" . }}"
{{- end }}
