---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-database
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata-database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "epos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metadata-database
  template:
    metadata:
      labels:
        {{- include "epos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: metadata-database
    spec:
      {{- include "epos.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: metadata-database
        image: {{ .Values.images.metadata_database_image }}
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: {{ .Values.components.metadata_database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.components.metadata_database.password }}
        - name: POSTGRES_DB
          value: {{ .Values.components.metadata_database.db_name }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
      {{- include "epos.nodeSelector" . | nindent 6 }}
      {{- include "epos.tolerations" . | nindent 6 }}
      {{- include "epos.affinity" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-database
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata-database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    {{- include "epos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metadata-database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-database
  labels:
    {{- include "epos.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata-database
data:
  POSTGRES_HOST: metadata-database
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.components.metadata_database.user }}
  POSTGRES_PASSWORD: {{ .Values.components.metadata_database.password }}
  POSTGRES_DB: {{ .Values.components.metadata_database.db_name }}
