{{- if .Values.image_pull_secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: epos-registry-secret
  labels:
    {{- include "epos.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.image_pull_secrets.registry_server .Values.image_pull_secrets.registry_username .Values.image_pull_secrets.registry_password .Values.image_pull_secrets.registry_email (printf "%s:%s" .Values.image_pull_secrets.registry_username .Values.image_pull_secrets.registry_password | b64enc) | b64enc }}
{{- end }}
